name: Build

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ build-essential \
          qt6-base-dev qt6-base-dev-tools qt6-tools-dev qt6-tools-dev-tools \
          qt6-charts-dev libqt6sql6-sqlite

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build -j $(nproc)

    - name: Install
      run: cmake --install build --prefix dist

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Foodcoop
        path: dist
